---
- name: Install hyprland
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - hyprland

- name: Install hyprland extras
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - conky
    - dmenu
    - dunst
    - feh
