---
- name: Install hyprland
  become: true
  ansible.builtin.apt:
    name:
      - hyprland
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Install hyprland extras
  become: true
  ansible.builtin.package:
    name:
      - conky
      - dmenu
      - dunst
      - feh
    state: present
  when: ansible_os_family == 'Debian'
