---
- name: Install hyprland
  become: true
  ansible.builtin.apt:
    name:
      - hyprland
    update_cache: true
    cache_valid_time: 3600

- name: Install hyprland extras
  become: true
  ansible.builtin.package:
    name:
      - conky
      - dmenu
      - dunst
      - feh
    state: present
