---
- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags:
        - hyprland
        - hyprland:install
  when: install | default(true) | bool
  tags:
    - hyprland
    - hyprland:install

- name: Uninstall
  ansible.builtin.include_tasks:
    file: uninstall.yml
    apply:
      tags:
        - hyprland
        - hyprland:uninstall
  when: not (install | default(true) | bool)
  tags:
    - hyprland
    - hyprland:uninstall
