---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: arch
    image: jahrik/docker-archlinux-ansible
    pre_build_image: true
    ulimits:
      - nofile:1024:524288
provisioner:
  name: ansible
verifier:
  name: ansible
